 SELECT A.DRUG_INGREDIENT_CODE, COUNT(A.DRUG_INGREDIENT_CODE) FROM DRUG_2015 A, BARCODEDATA B 
    WHERE A.DRUG_INGREDIENT_CODE = B.DRUG_INGREDIENT_CODE
    AND B.ATC_CD like 'N06A%'
    GROUP BY A.DRUG_INGREDIENT_CODE
    order by count(DRUG_INGREDIENT_CODE) desc;
    
    select * from drug_2014;
    
    select * from BARCODEDATA where ATC_CD like '%N06A';
    
     CREATE TABLE Drug_2015_2
   (	
   	"BASE_YEAR" NUMBER(4,0), 
	"USER_ID" NUMBER(10,0), 
	"PRES_ID" NUMBER(10,0), 
	"SERIAL_NUM" NUMBER(4,0), 
	"SEX" NUMBER(1,0), 
	"AGE_CODE" NUMBER(2,0), 
	"SIDO_CODE" NUMBER(2,0), 
	"RECUPERATE_DATE" VARCHAR2(20 BYTE), 
	"DRUG_INGREDIENT_CODE" VARCHAR2(20 BYTE), 
	"DOSE_ONCE" FLOAT(126), 
	"DOSE_ONEDAY" NUMBER(4,0), 
	"DOSE_DAYS" NUMBER(4,0), 
	"UNIT_COST" NUMBER(6,0), 
	"PRICE" NUMBER(10,0)
   );